### ISSUE TITLE
Unwanted PKGBUILD parts

### ISSUE THREAD

**Issue by shyaminayesh** [unmellow/lokinet-aur#1]
If we are not doing anything with the followings we don't need them in PKGBUILD file.

`conflicts=()
replaces=()
backup=()
options=()
install=`

**Comment by unmellow** [comment]
thanks but building from source doesn't work 
it worked when i git cloned the repo manually a while ago
witch is why a was shiping a the git repo here
i will try to get it to work later right now 
i need a way to setcap on the lokinet because right now it just doesn't work
also ver 0.6.4 has a bug so i'm using ver 0.7.0

**Comment by unmellow** [comment]
i forgot to say thanks so thanks so much for all the help
